motion_path: "data/lafan1_retargeted/g1/walk1_subject1.csv"

actor_hidden_dim: [256, 256]
critic_hidden_dim: [256, 256]

lr: 0.0003
weight_decay: 0.0001
gamma: 0.99
tau: 0.005
batch_size: 256
buffer_size: 1000000
total_steps: 2000000
learning_starts: 10000
gradient_steps: 4 #WAS 8

log_freq: 1000
save_freq: 50000